[NAMA SALES]
DSR - Kristia Devi

[KODE PELANGGAN]
PW-2063
PW-2048
KOSONG

[NAMA SALES]
C - Samsul Aziz

[KODE PELANGGAN]
PWT-3158
PWT-2068

[PERUSAHAAN]
PTM

[DIVISI]
PCMO

[TANGGAL]
03/08/2026

[INPUT]
ASTRI

[GIRO]
giro_stats = Ya
giro_cut = 1000

[PPRINT]
status = No

[SS]
url = 
sheet_name = LPH PCMO 2026

[PENDING]
pend_stats = Ya
pend_url = 
pend_sheet = 
pend_col_key = 
pend_col_ret = 

[MASTER]
masdatus = Ya
url = 
mas_sheet = Customer PCMO
mas_col_key = NOPEL
mas_col_ret = NAMA PELANGGAN
